apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-java-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-java-app
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80

