apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-java-app

